name: Build & Push - NGINX

on:
  push:
    branches: ["main"]
    paths:
      - "appgestaoti-Nginx/Dockerfile"
      - "appgestaoti-Nginx/prod/default.conf"
      - ".github/workflows/docker-nginx.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ghcr.io/devrafaelrabelo/appgestaoti-nginx:latest
