name: Build & Push - AppGestaoTI NGINX

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/docker-nginx.yml"
      - "Dockerfile"
      - "Dockerfile.prod"
      - "prod/**"
      - "dev-container/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build e Push da imagem NGINX
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ghcr.io/devrafaelrabelo/appgestaoti-nginx:latest
